### Лог сервиса
POST http://127.0.0.1/api/log
Accept: application/json
Content-Type: application/json
Bearer: 8bb042b0-9a41-48c3-bbea-3a4ae215c8bc

{
  "key": "request.test",
    "freq": "HOURLY",
    "count": 5,
    "interval": 1,
    "status": true
}


